[package]
name = "libsql-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
libsql = { path = "../../libsql", default-features = false, features = ["core"] }
wasm-bindgen = "0.2"
